trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

jobs:
  - job: Test
    condition: |
      and(
        not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')),
        or(
          eq(variables['Build.Reason'], 'PullRequest'),
          eq(variables['Build.SourceBranch'], 'refs/heads/master')
        )
      )
    strategy:
      matrix:
        windows2016:
          imageName: "vs2017-win2016"
        windows2019:
          imageName: "windows-2019"
      maxParallel: 2

    pool:
      vmImage: $(imageName)

    steps:
      - template: windows-dependencies.yml
        parameters:
          rustup_toolchain: '1.41.0-x86_64-pc-windows-msvc'
      - checkout: self
        submodules: recursive
      - script: cargo test
        displayName: Run unit tests
